sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
  - npm install -g @angular/cli
  - npm install -g karma
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: npm install

before_script:
  - greenkeeper-lockfile-update
  - ng build

script: karma start karma.conf.js --single-run

after_script: greenkeeper-lockfile-upload
